<template>
  <div>
    <p class="title">privacy Policy</p>
    <p class="center">1) Server Logs</p>
    <p class="text">
      Our servers automatically collect certain data from every user that visits our website including: IP address,
      browser type, browser language, and the date of the request. We use this data to analyze the statistics of our
      website to improve the user experience. We do not collect any personal information (such as your name, phone
      number, or email address) in our logs. We do not share this data with any third party networks.
    </p>
    <p class="center">2) Cookies</p>
    <p class="text">
      The Site also uses the third party web analytics service "Google Analytics" (GA), by Google, Inc. GA use
      "cookies", which are text files placed on your computer, to help the website analyze how users use the site. The
      information generated by the cookie about your use of the website (including your IP address) will be transmitted
      to and stored by Google on servers in the United States. Google will use this information for the purpose of
      evaluating your use of the website, compiling reports on website activity for website operators and providing
      other services relating to website activity and internet usage. Google may also transfer this information to third
      parties where required to do so by law, or where such third parties process the information on Google's behalf.
      Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by
      selecting the appropriate settings on your browser, however please note that if you do this you may not be able to
      use the full functionality of this website. No personal information (like your name, email or phone number) is
      being gathered with cookies. By using this Site, you consent to the processing of data about you by Google in the
      manner and for the purposes set out above.
    </p>
    <p class="center">3) Flash Shared Objects</p>
    <p class="text">
      Most of our games hosted on this website use Flash technology and are Flash Games. These Flash Games may collect
      data and store them as textfiles on your computer. We have no control over what data is stored as these flash
      games are produced by third parties. We are not responsible for any of the privacy practices of third party games
      hosted on our website.
    </p>
    <p class="center">4) Third Party Advertising</p>
    <p class="text">
      We use many different third party advertising agencies to serve advertisements on our website. These companies use
      cookies to store information about your browsing activity and visits to our website and other sites. You have the
      option to deny these cookies my changing your browser settings.
    </p>
    <p class="center">5) Google Adsense</p>
    <p class="text">
      Delivered by Google, Inc., may make use of one or more "DoubleClick DART Cookies". DART cookies store and collect
      data on your computer about your browsing activity. Google may use this data to show advertisements on this Site
      based on your browsing activity. You can choose to opt out of Google's use of cookies by visiting:
      https://www.google.com/policies/technologies/ads/ the Google ad and content privacy policy. Opt Out From Online
      Behavioral Advertising By Participating Companies: http://www.aboutads.info/choices/
    </p>

    <p class="center">6) Contact Via Email</p>
    <p class="text">
      When using our contact form to contact us via email, you are providing us with certain personal information that
      includes: your name and email address. This information is only used to assist you in solving your inquiry,
      request, or submissions. We respect the privacy concerns of our visitors and we do not sell or disclose this
      personal information.
    </p>

    <p class="center">7) Links</p>
    <p class="text">
      We may keep statistics on our internal links (links to other pages on our website) and external links (links to
      other websites) in order to track the number of clicks each link gets. These statistics are only used to help
      improve our site. We are not responsible for the privacy practices or content of websites that we link to from our
      website.
    </p>

    <p class="center">8) Security</p>
    <p class="text">
      We take the appropriate security measures to make sure that your personal information is protected against theft,
      unauthorized access, disclosure, copying, modification, or destruction.
    </p>

    <p class="center">9) IP Addresses</p>
    <p class="text">Playing Fun Games may collect your IP Address to use for security purposes.</p>
  </div>
</template>

<style scoped lang="scss">
  p.center {
    margin: 0 5px;
    text-align: center;
  }

  p.title {
    font-weight: bold;
    text-align: left;
    border-bottom: .5px solid #ccc;
  }

  p.text {
    text-indent: 24px;
  }

  div {
    margin: 10px 0;
  }

  p {
    padding: 5px;
    font-size: 12.67px;
    line-height: 15px;
    color: #000;
    text-align: center;
    // border: 1px solid;
    // word-wrap: break-word;

    // word-break: break-all;
  }
</style>
